name: Deploy and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest


    steps:
    # Étape 1 : Vérifiez le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Étape 3 : Configurez Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Étape 4 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 5 : Lancer les tests unitaires
    - name: Run unit tests
      run: pytest

    # Étape 6 : Construire et pousser l'image Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/maxwap/my-flask-app:latest
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
