name: Deploy and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  write_package: true


jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifiez le code source
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Étape 2 : Configurez Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Lancer les tests unitaires
    - name: Run unit tests
      run: pytest

    # Étape 5 : Construire et pousser l'image Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/maxwap/my-flask-app:latest